env:
  - "DB=mysql"
  - "DB=postgresql"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake --trace fulcrum:setup db:setup"
rvm:
  - 1.9.2
  - 1.9.3
script:
  - "bundle exec rspec spec"
  - "bundle exec rake --trace jasmine:ci"
